Repository daniabee/whats-cookin-good-lookin, pull requests merged in 2022-10, with the labels that each got.

#9 Add a directory for samples
  sampleSets/ingredientsSample.js
Labels: documentation

#11 Add ingredient class file
  sampleSets/Ingredients.js
  src/classes/Ingredient.js
  test/Ingrediants.js
Labels: documentation

#13 Andy/feature/ingredient sections
  sampleSets/Ingredients-sample.js
  src/classes/Ingredient-class.js
  src/classes/Ingredient.js
  test/Ingrediants.js
  test/Ingredient
  test/Ingredient-test.js
Labels: documentation

#15 Courtney lippman/recipe repository tests
  sampleSets/recipeRepositorySample.js
  src/classes/RecipeRepository.js
  test/RecipeRepository-test.js
Labels: enhancement

#27 All/feature/final fetch
  src/apiCalls.js
  src/classes/RecipeRepository.js
  src/scripts.js
Labels: enhancement

#33 Andy/fix/homepage css
  dist/index.html
  src/styles.css
Labels: enhancement, HTML structure

#47 Dani andy/feature/functional search bar
  src/scripts.js
Labels: enhancement, DOM

#52 add the ability to clear out the search bar input when focused
  dist/index.html
  src/scripts.js
Labels: enhancement, HTML structure

#57 Bugfix recipe thumbnail layout
  src/styles.css
Labels: bug

#55 add a group readme file
  src/groupREADME.md
Labels: documentation

#59 Andy/courtney/fix filter search bar
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement, User Experience Item
